version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_DB: testdb
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1'"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  tests:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
    environment:
      POSTGRES_CONNECTION_STRING: "Host=postgres;Database=testdb;Username=postgres;Password=password"
      SQLSERVER_CONNECTION_STRING: "Server=sqlserver;Database=testdb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true"
    volumes:
      - .:/src